### PR TITLE
Layout guides and iOS 9 support

### PR DESCRIPTION
**Pull request by CraigSiemens**
For https://github.com/SnapKit/Masonry/issues/207

This adds properties on UIViewController to get the MASViewAttribute for top and bottom layout guides. This works on iOS 7, 8 and 9.

### CODE REVIEW

**Comment by cloudkite** [comment]
@CraigSiemens Awesome work! Sorry for the delay!

**Comment by neilkimmett** [comment]
Would you mind doing a new CocoaPods release with this in?

**Comment by cloudkite** [comment]
This is now on cocoapods in v0.6.2

**Comment by neilkimmett** [comment]
Nice one, thanks @cloudkite :blush:

**Comment by johnryan** [comment]
@cloudkite I'm still seeing the issue

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UILayoutSpacer mas_bottom]: unrecognized selector sent to instance 0x14ee7c4d0'
```

in 0.6.2 

when I do this

```
UIView *topLayoutGuide = (UIView *)self.topLayoutGuide;
make.top.equalTo(topLayoutGuide.mas_bottom).offset(10);
```

Any suggestions?

**Comment by CraigSiemens** [comment]
That way no longer works in iOS 9. You will need to use the new layout guide attributes added to UIViewController by this pull request.

```objc
make.top.equalTo(self.mas_topLayoutGuide).offset(10);
```

**Comment by johnryan** [comment]
Ah, got it thanks

**Comment by kmikael** [comment]
I tried `0.6.2` and the current master branch and this issue is not fixed for me. I'm using Xcode 7.0 (7A218), that is the GM.

```
-[_UILayoutSpacer mas_bottom]: unrecognized selector sent to instance 0x7fc43cd6e4d0
``

**Comment by CraigSiemens** [comment]
Casting the `topLayoutGuide` to a `UIView`no longer works in iOS 9. The proper way to layout using the layout guides is to use the `mas_topLayoutGuide` and `mas_bottomLayoutGuide` on `UIViewContorller`

It should look like this
```objc
make.top.equalTo(self.mas_topLayoutGuide).offset(10);
```

There is also an example in [MASExampleLayoutGuideViewController.m](https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleLayoutGuideViewController.m)

**Comment by kmikael** [comment]
Thanks. Sadly, we are using a closed-source third party SDK that uses Masonry, so we can't do anything about it. But just now we found a way to swizzle the required methods into `_UILayoutSpacer` and now it works again. Hopefully that third party SDK will be updated soon.

**Pull request merged**
