### PR TITLE
updated .travis.yml to use xcode 8

### PR DESCRIPTION
**Pull request by fabb**

### CODE REVIEW

**Comment by fabb** [comment]
very strange:
```
▸ Signing /Users/travis/Library/Developer/Xcode/DerivedData/Masonry-frwsrzkwrympwdbvwexxbpkyckdt/Build/Products/Debug-iphonesimulator/MasonryTestsLoader.app/PlugIns/Masonry\ iOS\ Tests.xctest
** TEST FAILED **
The command "xcodebuild -workspace 'Masonry.xcworkspace' -scheme 'Masonry iOS Tests' -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' clean test ARCHS=i386 VALID_ARCHS=i386 ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c" exited with 65.
```

Running tests locally works fine :-/

**Comment by fabb** [comment]
hmmm, when removing `| xcpretty -c` it works fine on travis
https://travis-ci.org/SnapKit/Masonry/builds/168841142

**Comment by fabb** [comment]
probably the issue has to do with `xcpretty` and some of the xctest helper libs
https://github.com/fastlane/fastlane/issues/3886#issuecomment-224884332

**Comment by fabb** [comment]
Yay, finally works!

`XCTestObserver` should no longer be used as it's deprecated, created another issue for that: #394

**Comment by robertjpayne** [comment]
Thanks!

**Pull request merged**
