### PR TITLE
make loops run faster

### PR DESCRIPTION
**Pull request by flexih**

### CODE REVIEW

**Comment by cloudkite** [comment]
@flexih I'd actually prefer to depreciate `NSArray+MASAdditions` as this feels like it belongs in user land or as a third party library since it contains code which prescribes very specifically how to layout an array of views. I think this kinda logic would be better if its under direct control of the App developer and not part of Masonry so it can be tweaked to suit the project. cc original PR author @danielrhammond

**Comment by flexih** [comment]
Ah, I think it's kind of useful.

**Comment by Panajev** [comment]
Unless it introduced a regression and you can provide some sort of performance improvement metric, I would agree that merging this is in order regardless of the longer term solution of putting this responsibility in developers' hands...

**Comment by danielrhammond** [comment]
Cursory review of the diff looks like a good change (man its jarring to see old obj-c code after being in swift land for a while!), not sure how it would lead to noticeable performance improvements unless you had fairly large arrays of views since it is just removing two if checks in the loop. But it is much easier to read and removes this hideous statement I wrote: `if (i == (CGFloat)self.count - 1) {`

I agree in general with @cloudkite that this seems like more appropriate as a user land extension, think its totally reasonable to deprecate. This was probably always the case, but especially so now that the feature overlaps the iOS 9 `UIStackView`.

**Comment by flexih** [comment]
It's test to be at the same level time consuming.

**Pull request closed without merging**
