### PR TITLE
bug fix: use greaterThanOrEqualTo or lessThanOrEqualTo to add a attri…

### PR DESCRIPTION
**Pull request by game3108**
I guess it is a bug.
When use lessThanOrEqualTo or greaterThanOrEqualTo to add a array attribute, the viewConstraint layoutRelation is NSLayoutRelationEqual(default).

### CODE REVIEW

**Comment by robertjpayne** [comment]
@game3108 could you please update the failing test and ensure it passes? I think the test is bad too though!

**Comment by robertjpayne** [comment]
@game3108 thannks! I'll merge this as soon as Travis finishes

**Comment by game3108** [comment]
Thanks. :)

**Comment by robertjpayne** [comment]
No thank you!

**Pull request merged**
