### PR TITLE
Added TVOS

### PR DESCRIPTION
**Pull request by mariohahn**
Check out that shit 🍻

### CODE REVIEW

**Comment by cloudkite** [comment]
@mariohahn :+1: awesome!

would prefer to just use 

`TARGET_OS_IPHONE || TARGET_OS_TV`

instead of

`TARGET_OS_IPHONE_AND_OS_TV `

similar to how its done in AFNetworking

https://github.com/AFNetworking/AFNetworking/compare/3_0_0_branch

**Comment by mariohahn** [comment]
You don't think that it is easier to understand it like that? Otherwise i can send you another Pull request.

**Comment by cloudkite** [comment]
@mariohahn I get where you are coming from, but ideally would prefer not to add any extra macro definitions when possible

**Comment by robertjpayne** [comment]
Agree with @cloudkite in the future tvOS and iOS may diverge features and a joined macro is less flexible. @mariohahn if you can update the PR we'll merge it!

**Comment by mariohahn** [comment]
I changed it (:

**Comment by mariohahn** [comment]
Any News about this?

**Comment by cloudkite** [comment]
@mariohahn looks great! sorry for delay.

only change I think would be good is too include backwards compatibility for previous versions of Xcode see

https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking.podspec#L15-L27

**Comment by mariohahn** [comment]
(:

**Comment by mariohahn** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0 💪🏼

**Comment by cloudkite** [comment]
Thanks again !

**Comment by mariohahn** [comment]
could you please update the pod?

**Comment by robertjpayne** [comment]
@mariohahn pushed :)

**Pull request merged**
