### PR TITLE
Add mas_replaceConstraints method to View-MASAdditions

### PR DESCRIPTION
**Pull request by dourgulf**
Usecase:

self is the super view

view constraint like this:

[[headerView][scrollView]-------]

Initailly scrollView's tailing equalTo self

If I want to change the scrollView's traling from self to headerView's trailing, I must remember the constraint with a variable, uninstall it and update it.

```
MASConstraint *scrollViewTrailing;
[scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.leading.equalTo(HeaderView.mas_trailing);
    make.top.equalTo(self);
    make.bottom.equalTo(self);
    scrollViewTrailing = make.trailing.equalTo(self);
}];

// change constraint:
[scrollViewTrailing uninstall];
[scrollView mas_updateConstraints:^(MASConstraintMaker *make) {
	CGRect frame = scrollView.frame;
    if (frame.size.width <= 0) {
    	// make width full
        scrollViewTrailing = make.trailing.equalTo(self);
    }
    else {
    	// make width to zero
        scrollViewTrailing = make.trailing.equalTo(HeaderView.mas_trailing);
    }
}];
```
============================================================
If add a replaceConstraints method, we can do it directly no additional variable anymore.

```
[scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.leading.equalTo(HeaderView.mas_trailing);
    make.top.equalTo(self);
    make.bottom.equalTo(self);
    make.trailing.equalTo(self);
}];
// change constraint:
[scrollView mas_replaceConstraints:^(MASConstraintMaker *make) {
	CGRect frame = scrollView.frame;
    if (frame.size.width <= 0) {
    	// make width full
        make.trailing.equalTo(self);
    }
    else {
    	// make width to zero
        make.trailing.equalTo(HeaderView.mas_trailing);
    }
}];
```

### CODE REVIEW

**Comment by cloudkite** [comment]
@dourgulf is this not doing the same thing as `mas_remakeConstraints`? 
see https://github.com/SnapKit/Masonry/blob/master/Masonry/View%2BMASAdditions.m#L29

**Comment by dourgulf** [comment]
@cloudkite Oh, I am misunderstood the usage of mas_remakeConstraints, I thought it shout remake all previous contraint. Ok, I will cancel this pull request.

**Comment by dourgulf** [comment]
Oh, No, in fact mas_replaceConstraints is difference from mas_remakeConstraints.
mas_remakeConstraints will remove all existing contraints, but my requirement is only remove the constraints in mas_replaceConstraints. For example if use mas_remakeConstraints, my example code must be like this:
```
[scrollView mas_remakeConstraints:^(MASConstraintMaker *make) {
    CGRect frame = scrollView.frame;
    if (frame.size.width <= 0) {
	    make.leading.equalTo(HeaderView.mas_trailing);
	    make.top.equalTo(self);
	    make.bottom.equalTo(self);
        // make width full
        make.trailing.equalTo(self);
    }
    else {
	    make.leading.equalTo(HeaderView.mas_trailing);
	    make.top.equalTo(self);
	    make.bottom.equalTo(self);
        // make width to zero
        make.trailing.equalTo(HeaderView.mas_trailing);
    }
}];
```
It will make much duplicated code for create and remake.

**Comment by cloudkite** [comment]
@dourgulf Oh ok, you want something slightly different where it only replaces one constraint.

why not do?
```
[scrollView mas_remakeConstraints:^(MASConstraintMaker *make) {
    CGRect frame = scrollView.frame;
    make.leading.equalTo(HeaderView.mas_trailing);
    make.top.equalTo(self);
    make.bottom.equalTo(self);
    if (frame.size.width <= 0) {
        // make width full
        make.trailing.equalTo(self);
    }
    else {
        // make width to zero
        make.trailing.equalTo(HeaderView.mas_trailing);
    }
}];
```

**Comment by cloudkite** [comment]
hesitant to introduce something like what you have proposed because it can lead to confusing behaviour when you have more than one constraint on an attribute.

take for example
```
[scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
    make.trailing.greaterThanOrEqualTo(HeaderView.mas_trailing);
    make.trailing.lessThanOrEqualTo(self);
}];
```

It's not clear what the end result of the following code will be
```
[scrollView mas_replaceConstraints:^(MASConstraintMaker *make) {
   make.trailing.equalTo(2000);
}];
```

This is the same problem with `mas_updateConstraints` alot of people have found it confusing and hence its often better just to use `mas_remakeConstraints`

**Comment by cloudkite** [comment]
If you use a similar pattern to this example https://github.com/SnapKit/Masonry/blob/master/Examples/Masonry%20iOS%20Examples/MASExampleRemakeView.m

you shouldn't need to repeat any constraint code

**Comment by dourgulf** [comment]
I agree with you, mas_remakeConstraints almost OK, the only problem is the duplcated code when remaking, you shoult rewrite almost all constraint which you had write when make the initail constrait, and only change one constraint, it's a bad code smell

**Comment by cloudkite** [comment]
@dourgulf can you please provide an example of how layout code is duplicated? Using the example given below can't see any reason that you need to duplicate code when using `mas_remakeConstraints`.

```
[scrollView mas_remakeConstraints:^(MASConstraintMaker *make) {
    CGRect frame = scrollView.frame;
    make.leading.equalTo(HeaderView.mas_trailing);
    make.top.equalTo(self);
    make.bottom.equalTo(self);
    if (frame.size.width <= 0) {
        // make width full
        make.trailing.equalTo(self);
    }
    else {
        // make width to zero
        make.trailing.equalTo(HeaderView.mas_trailing);
    }
}];
```

**Comment by cloudkite** [comment]
closed due to inactivity, please reopen if you want to discuss further

**Pull request closed without merging**
